In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [8]:
# Load dataset
df = pd.read_csv("../datasets/winequality.csv", sep=',')

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [11]:
df.isnull()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,False,False,False,False,False,False,False,False,False,False,False,False,False
1139,False,False,False,False,False,False,False,False,False,False,False,False,False
1140,False,False,False,False,False,False,False,False,False,False,False,False,False
1141,False,False,False,False,False,False,False,False,False,False,False,False,False
1142,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.shape

(1143, 13)

In [9]:
# Convert regression → classification
df['quality'] = df['quality'].apply(lambda x: 1 if x >= 6 else 0)

# Split features & target
X = df.drop('quality', axis=1)
y = df['quality']

In [10]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
# Model
rf = RandomForestClassifier(n_estimators=150, random_state=42)
rf.fit(X_train, y_train)

# Prediction
y_pred = rf.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7903930131004366

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.76      0.76       102
           1       0.81      0.81      0.81       127

    accuracy                           0.79       229
   macro avg       0.79      0.79      0.79       229
weighted avg       0.79      0.79      0.79       229

In [14]:
importance = rf.feature_importances_

features = X.columns

print("\nFeature Importance:")
for f, imp in zip(features, importance):
    print(f"{f}: {imp:.4f}")

Feature Importance:
fixed acidity: 0.0589
volatile acidity: 0.1170
citric acid: 0.0596
residual sugar: 0.0466
chlorides: 0.0644
free sulfur dioxide: 0.0512
total sulfur dioxide: 0.0840
density: 0.0789
pH: 0.0564
sulphates: 0.1341
alcohol: 0.1764
Id: 0.0724